resources:
  pipelines:
    gdelt_narrative_pipeline:
      name: gdelt-narrative-pipeline
      catalog: ${var.catalog}
      schema: ${var.schema}
      serverless: true
      channel: CURRENT
      continuous: false

      libraries:
        - notebook:
            path: ${workspace.file_path}/src/gdelt_narrative/pipeline/bronze
        - notebook:
            path: ${workspace.file_path}/src/gdelt_narrative/pipeline/silver
        - notebook:
            path: ${workspace.file_path}/src/gdelt_narrative/pipeline/gold

      configuration:
        pipelines.reset.allowed: "true"
